version: '3.7'

services:

    report_database:
      image: mariadb:latest
      volumes:
        - /var/data/mariadb:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=da7tnqw79e5v6nbqw3v5rtwev57mtwm5vrftw75vfnm275v2  #change bevore deploy
        - MYSQL_USER=report
        - MYSQL_PASSWORD=TuqWuRdjLbSPTRqBnnEU24ZSsqAy9b6LbXA8ZuQg  #change bevore deploy
        - MYSQL_DATABASE=report
      restart: unless-stopped
      container_name: report_database
      hostname: report_database

    report_microservice:
      image: eedu/reportms
      ports:
        - 5000:5000
      environment:
        - DATABASE_HOSTNAME=report_database
        - DATABASE_PORT=3306
        - DATABASE_USERNAME=report
        - DATABASE_PASSWORD=TuqWuRdjLbSPTRqBnnEU24ZSsqAy9b6LbXA8ZuQg  #change bevore deploy
        - DATABASE_DATABASE=report
        - JWT_SECRET=test     #change bevore deploy
        - SERVICE_SECRET=test #change bevore deploy
      restart: unless-stopped 
      container_name: report_microservice
      depends_on:
        - report_database