version: '3.7'

services:

    report_database:
      image: postgres:latest
      environment:
        - POSTGRES_DB=report
        - POSTGRES_USER=report
        - POSTGRES_PASSWORD=test
      restart: unless-stopped
      container_name: report_database
      hostname: report_database

    report_ms:
      image: report-ms
      environment:
        - DB_HOSTNAME=report_database
        - DB_USERNAME=report
        - DB_PASSWORD=test  #change bevore deploy
        - DB_DATABASE=report
        - conf_mode=deploy
        - JWT_Secret=test #change bevore deploy
        - MS_Secret=test #change bevore deploy
      build:
        context: .
        dockerfile: Dockerfile-flask
      volumes:
        - "./:/app"
      restart: unless-stopped
      container_name: report_ms
      depends_on: 
        - report_database
    
    nginx:
      image: report-nginx
      build:
        context: .
        dockerfile: Dockerfile-nginx
      ports:
        - 5000:80
      container_name: report_nginx
      depends_on:
        - report_ms